### ISSUE TITLE
下载进度条有bug

### ISSUE THREAD

**Issue by redapple0204** [PeterDing/aget#2]
下载速度在进度条里显示0k，然而任务管理器看大约1m/s
![2](https://cloud.githubusercontent.com/assets/16254644/23099318/9b7fd2e4-f69e-11e6-9847-61e4a6ca838b.PNG)

**Comment by PeterDing** [comment]
你这是开太多链接了😱

`-s`指定同时下载的并发链接数。
开太多，服务器就被你玩烂了。
建议不要多于200个。

一个链接接收到一个`-k`的数据才会发给程序显示速度。
你`-s`多了，那一个链接接收数据的速度就小了，速度显示就慢了。

**Comment by PeterDing** [comment]
一般我用 `-s 60 -k 60k` 就能满速。

**Comment by redapple0204** [comment]
好吧...但是对百度云拉黑的账号只有单线程10k/s啊！

**Comment by redapple0204** [comment]
另外-k后面的建议是多少比较好呢？

**Comment by PeterDing** [comment]
我这里用 `-s 60 -k 60k`，就很好。
自己的环境，参数自己试吧。

**Comment by redapple0204** [comment]
好的，谢谢。
另外这样下文件速度很不稳耶？有时候最快能3M/s最慢才几k/s

**Comment by PeterDing** [comment]
我也遇到这种情况，抱歉目前无法解决，除非买 svip

**Comment by redapple0204** [comment]
好吧，谢谢了。
