### ISSUE TITLE
大佬...win下用cmder/cygwin还是没法运行啊

### ISSUE THREAD

**Issue by redapple0204** [PeterDing/aget#4]
表示现在开一个虚拟机来下载好蛋疼....作者有没有支持windows的想法？

**Comment by PeterDing** [comment]
我想想办法，看看有无可能在windows上不太复杂地使用aget，如果没有，可以试试用其他跨平台语言重写。
最近在学rust，我可以试试用rust实现一个。

**Comment by redapple0204** [comment]
@PeterDing 好的，thx
顺便问下python非得用httptool吗，如果换个别的方式呢？

**Comment by PeterDing** [comment]
@redapple0204 [httptools](https://github.com/MagicStack/httptools)是用cython写的http协议解析库，比原python代码快很多，[mugen](https://github.com/PeterDing/mugen)需要。

**Comment by redapple0204** [comment]
@PeterDing 长知识了，thx
