### ISSUE TITLE
更新之后好像有点小问题

### ISSUE THREAD

**Issue by redapple0204** [PeterDing/aget#5]
更新之后，用超高线程（因为百度云现在限速太恶心了，所以只能用超高线程来破解），本来只有的问题是程序内速度显示错误，但是现在的话下载也狂报错了....
![](https://cloud.githubusercontent.com/assets/16254644/25278826/1ca4d2a8-26d7-11e7-8016-3e0458ac7494.PNG)

**Comment by redapple0204** [comment]
PS:刚刚回退到了老版本就没这个情况了，是不是更改了什么下载方式？

**Comment by PeterDing** [comment]
[mugen](https://github.com/PeterDing/mugen) 更新了，会默认输出 IO的错误。
`Too many open files` 是指程序打开的链接数过多，超过 `process resource limits`。

如果要增加 `resource limits`，可以参考
http://www.computerworld.com/article/2693414/setting-limits-with-ulimit.html

**Comment by redapple0204** [comment]
@PeterDing 那请问会对下载的文件有影响吗，例如不完整？

**Comment by PeterDing** [comment]
@redapple0204 不会，你可以同时用 `wget` 和 `aget` 下同一个文件，然后 md5 检校试试。

**Comment by redapple0204** [comment]
@PeterDing 哦，好的，thx
