### ISSUE TITLE
关于下载使用-t1参数和两个程序同时开启还有询问最佳配置的方案

### ISSUE THREAD

**Issue by redapple0204** [PeterDing/aget#6]
作者您好，我在使用软件的过程中遇到了一些问题
1.我看到帮助文档里面有关于-t（timeout）参数的使用说明，于是我加上了-t1参数，结果程序就没有下载了，程序内部给出的错误是
>ERROR:root:[<function Connection.connect at 0x7fb9ac4fa488>]: CancelledError()

2.今天我和朋友弄了一个破解百度云的网站，188.166.240.234，使用的是您的程序，但是请问为什么两个人同时下载的时候会导致无法下载（即aget仍在运行，但是下载速度为0）

3.我的下载vps是2Gbps的网络，结果现在使用的-s 650k -k 130k（目前试过最好的速度了）也只有100mbps/s，和宽带原有的速度差多了，请问您觉得要用什么参数才会更好呢？

期待您的回复。

**Comment by redapple0204** [comment]
哦还有一个问题，就是下载到最后的时候经常会卡0k/s，要等很久，请问有什么办法解决么？

**Comment by PeterDing** [comment]
`timeout` 是指一个请求从开始到 `timeout` 这么多秒内如果还没结束则抛出 Timeout 异常。
`-t 1`是指每个请求只能进行 1 秒。;)

[CancelledError](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.CancelledError) 得抛出可能与 `-t 1` 有关，1 秒后 future 被关了。具体情况要看你的 case 了。

最后会卡在 `0k/s` 没有太好的解决方法。这是因为最后几个请求受限于 baidu，如果 baidu 不给速度，那只有等。

如果你是一个账号几个人用，这要 baidu 不封你都难。。。

PS:
`-s 650k` 开太多了，建议小于 2048。

**Comment by redapple0204** [comment]
@PeterDing 1.哦好的，谢谢
2.但是这传递的是不同人的cookies，应该问题不大吧
3.啊啊啊我说错了，是 -s 650，因为我的vps超过700程序会自己kill掉
但是又没有办法在-s不能超过650的情况下高速下载？

**Comment by PeterDing** [comment]
> vps超过700程序会自己kill掉

这个可能是因为 `file descriptor` 数量不够多，搜索 `ulimit linux` 看看。

**Comment by redapple0204** [comment]
@PeterDing 貌似是cpu占用到100%然后boom了吧

**Comment by redapple0204** [comment]
@PeterDing 我改成999999了，还是不行。

**Comment by PeterDing** [comment]
@redapple0204 `程序会自己kill掉` 是什么意思。程序报错才会结束进程吧，你尝试捕获一下出错信息，看看是怎么回事。

**Comment by redapple0204** [comment]
@PeterDing 我知道了，是我的内存不足，现在加了swap就不会了
感谢你的回复。
